# Generated by Django 4.0 on 2022-10-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
