# Generated by Django 4.0 on 2022-10-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace'),
    ]

    operations = [
    ]
