# Generated by Django 4.0 on 2022-10-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221014_1258'),
    ]

    operations = [
    ]
